# Generated by Django 4.2.2 on 2023-08-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
