# Generated by Django 4.2.2 on 2023-08-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_artist_alter_music_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['id']},
        ),
    ]
